In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
A = np.array([[1,2,3], [3,4,5]])
print(A)

[[1 2 3]
 [3 4 5]]


In [3]:
U, D, V = np.linalg.svd(A)

In [4]:
print(U)

[[-0.46410668 -0.88577931]
 [-0.88577931  0.46410668]]


In [5]:
print(D)

[7.97638869 0.61418515]


In [7]:
print(np.diag(D))

[[7.97638869 0.        ]
 [0.         0.61418515]]


In [8]:
print(V)

[[-0.39133557 -0.5605708  -0.72980603]
 [ 0.8247362   0.13817999 -0.54837623]
 [ 0.40824829 -0.81649658  0.40824829]]
