In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [3]:
A = np.array([[3, 2], [4,1]])
print(A)

[[3 2]
 [4 1]]


In [4]:
autovalores, autovectores = np.linalg.eig(A)


In [7]:
print(autovalores)
print(autovectores)

[ 5. -1.]
[[ 0.70710678 -0.4472136 ]
 [ 0.70710678  0.89442719]]


In [9]:
A_calc =  autovectores.dot(np.diag(autovalores)).dot(np.linalg.inv(autovectores))

In [10]:
print(A_calc)

[[3. 2.]
 [4. 1.]]


In [11]:
A = np.array([[3,2],[2,3]])
print(A)

[[3 2]
 [2 3]]


In [12]:
print(A == A.T)

[[ True  True]
 [ True  True]]


In [13]:
autovalores, autovectores = np.linalg.eig(A)
print(autovalores)
print(autovectores)

[5. 1.]
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [17]:
A_calc = autovectores.dot(np.diag(autovalores)).dot(autovectores.T)
print(A_calc)

[[3. 2.]
 [2. 3.]]
