In [1]:
import numpy as np

In [2]:
np.set_printoptions(suppress=True)

In [3]:
A = np.array([[3,1],[2,1]])
print(A)

[[3 1]
 [2 1]]


In [4]:
b = np.array([[1],[1]])

In [6]:
inversa_A = np.linalg.inv(A)
print(inversa_A)

[[ 1. -1.]
 [-2.  3.]]


In [7]:
x = inversa_A.dot(b)
print(x)

[[0.]
 [1.]]


In [9]:
print(A.dot(x))

[[1.]
 [1.]]


In [10]:
sol_2=inversa_A.dot(np.array([[3],[7]]))
sol_2

array([[-4.],
       [15.]])

In [11]:
print(A.dot(sol_2))

[[3.]
 [7.]]
