In [1]:
import numpy as np

### Matriz diagonal


In [2]:
vector = np.array([1,2,3,4,5])

matriz = np.diag(vector)

print(matriz)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


### Matriz diagonal no cuadradas


In [3]:
print(matriz[0:4,0:3])

[[1 0 0]
 [0 2 0]
 [0 0 3]
 [0 0 0]]


In [4]:
print(matriz[0:3,0:4])

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]]


In [9]:
A = np.diag([2,3,4,5])
print(A)

[[2 0 0 0]
 [0 3 0 0]
 [0 0 4 0]
 [0 0 0 5]]


In [12]:
v1 = np.array([[1,1,1,1]])
print(v1)

print(A.dot(v1.T))

[[1 1 1 1]]
[[2]
 [3]
 [4]
 [5]]


In [13]:
A_inv = np.diag([1/2, 1/3, 1/4, 1/5])
print(A_inv)

[[0.5        0.         0.         0.        ]
 [0.         0.33333333 0.         0.        ]
 [0.         0.         0.25       0.        ]
 [0.         0.         0.         0.2       ]]


In [15]:
identidad = A.dot(A_inv)
print(identidad)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [16]:
A_inv_cal = np.linalg.inv(A)
print(A_inv_cal)

[[0.5        0.         0.         0.        ]
 [0.         0.33333333 0.         0.        ]
 [0.         0.         0.25       0.        ]
 [0.         0.         0.         0.2       ]]


### Matriz simetrica


In [17]:
print(A.T)

[[2 0 0 0]
 [0 3 0 0]
 [0 0 4 0]
 [0 0 0 5]]


In [18]:
print(A)

[[2 0 0 0]
 [0 3 0 0]
 [0 0 4 0]
 [0 0 0 5]]


In [22]:
simetrica = np.array([[1,2,3],
                     [2,-1,7],
                     [3,7,11]])
print(simetrica)

[[ 1  2  3]
 [ 2 -1  7]
 [ 3  7 11]]


In [23]:
print(simetrica.T)

[[ 1  2  3]
 [ 2 -1  7]
 [ 3  7 11]]
