In [1]:
import numpy as np

In [14]:
escalar = 5.679
vector = np.array([2,3])
matriz = np.array([[1,2],[3,4],[5,6]])

In [19]:
A = matriz * vector

In [20]:
print(A)

[[ 2  6]
 [ 6 12]
 [10 18]]


### Producto interno de la matriz

In [16]:
B = matriz.dot (vector)

In [17]:
print(B)

[ 8 18 28]


In [21]:
C = np.dot(matriz, vector)
print(C)

[ 8 18 28]
