In [1]:
import numpy as np

In [2]:
A = np.array([[2,3],[5,7],[11,13]])
B = np.array([[1,3],[2,1]])
C = np.array([[3,1],[4,2]])

### Asociativa

A x (BXC) = (AXB) XC

In [3]:
ABC = A.dot(B.dot(C))
print(ABC)

[[ 60  26]
 [145  63]
 [295 129]]


In [8]:
AB_C = A.dot(B).dot(C)
print(AB_C)

[[ 60  26]
 [145  63]
 [295 129]]


### Distributiva

A X (B+C) = (AXB) + (AXC)


In [13]:
D = A.dot(B+C)
E = (A.dot(B))+(A.dot(C))

print(D)
print(E)


[[ 26  17]
 [ 62  41]
 [122  83]]
[[ 26  17]
 [ 62  41]
 [122  83]]


In [15]:
print(D==E)

[[ True  True]
 [ True  True]
 [ True  True]]


### Conmutativa

BXC = CXB


In [16]:
F = B.dot(C)

In [17]:
G = C.dot(B)

In [18]:
print(F==G)

[[False False]
 [False False]]


In [19]:
print(F)

[[15  7]
 [10  4]]


In [20]:
print(G)

[[ 5 10]
 [ 8 14]]


### Multiplicacion de vectores si es conmutativa


In [21]:
v1 = np.array([[2],[7]])
v2 = np.array([[3],[5]])

In [23]:
v1_tv2= v1.T.dot(v2)
v2_tv1 = v2.T.dot(v1)

In [24]:
print(v1_tv2)

[[41]]


In [25]:
print(v2_tv1)

[[41]]
