In [1]:
import numpy as np

np.set_printoptions(suppress=True)

In [2]:
A = np.array([[1,2], [3,4],[5,6]])
print(A)

[[1 2]
 [3 4]
 [5 6]]


In [3]:
U, D, V = np.linalg.svd(A)
print('U')
print(U)
print('D')
print(D)
print('V')
print(V)

U
[[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]
D
[9.52551809 0.51430058]
V
[[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]


In [4]:
D_pse = np.zeros((A.shape[0], A.shape[1])).T
print(D_pse)

[[0. 0. 0.]
 [0. 0. 0.]]


In [5]:
print('Valores_a_remplazar_en_D_pse')
print(D_pse[:D.shape[0], : D.shape[0]])

Valores_a_remplazar_en_D_pse
[[0. 0.]
 [0. 0.]]


In [6]:
print('Valores_que_pondremos_en_D_pse')
print(np.linalg.inv(np.diag(D)))

Valores_que_pondremos_en_D_pse
[[0.10498117 0.        ]
 [0.         1.94438824]]


In [7]:
print('D_pse')
D_pse[:D.shape[0], :D.shape[0]] = np.linalg.inv(np.diag(D))
print(D_pse)

D_pse
[[0.10498117 0.         0.        ]
 [0.         1.94438824 0.        ]]


In [8]:
A_pse = V.T.dot(D_pse).dot(U.T)
print(A_pse)

[[-1.33333333 -0.33333333  0.66666667]
 [ 1.08333333  0.33333333 -0.41666667]]


In [9]:
A_pse_calc = np.linalg.pinv(A)
print(A_pse_calc)

[[-1.33333333 -0.33333333  0.66666667]
 [ 1.08333333  0.33333333 -0.41666667]]


In [10]:
print(A_pse.dot(A))

[[ 1.  0.]
 [-0.  1.]]


In [11]:
np.set_printoptions(suppress = False)

In [12]:
print(A_pse.dot(A))

[[ 1.00000000e+00  4.44089210e-16]
 [-2.77555756e-16  1.00000000e+00]]


In [13]:
print(A.dot(A_pse))

[[ 0.83333333  0.33333333 -0.16666667]
 [ 0.33333333  0.33333333  0.33333333]
 [-0.16666667  0.33333333  0.83333333]]


In [14]:
A_pse_2 = np.linalg.inv(A.T.dot(A)).dot(A.T)
print(A_pse_2)

[[-1.33333333 -0.33333333  0.66666667]
 [ 1.08333333  0.33333333 -0.41666667]]
