In [1]:
import numpy as np

In [9]:
escalar = 5.679
vector = np.array([3,4,5])
matriz = np.array([[1,2],[3,4],[5,6]])


In [11]:
A = matriz.T + vector
A

array([[ 4,  7, 10],
       [ 5,  8, 11]])

In [10]:
C = matriz + 42
C

array([[43, 44],
       [45, 46],
       [47, 48]])

In [13]:
(matriz.shape)

(3, 2)

In [14]:
(vector.shape)

(3,)

In [16]:
D = matriz + np.array([[42],[42],[42]])
D

array([[43, 44],
       [45, 46],
       [47, 48]])