In [ ]:
import numpy as np

In [ ]:
escalar = 5.679
vector = np.array([3,4,5,6])
matriz = np.array([[1,2],[3,4],[5,6]])
tensor = np.array([
    [[1,2,3,30],[4,5,6,31],[7,8,932]],
    [[1,2,3,30],[4,5,6,31],[7,8,932]],
    [[1,2,3,30],[4,5,6,31],[7,8,932]],
])


<ipython-input-5-a2a0b9f892aa>:4: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  tensor = np.array([


In [ ]:
vector_t =vector.T
vector_t

array([3, 4, 5, 6])

In [ ]:
matriz_t = matriz.T
matriz_t 

array([[1, 3, 5],
       [2, 4, 6]])

In [ ]:
(matriz.shape)

(3, 2)

In [ ]:
(matriz_t.shape)

(2, 3)

In [ ]:
tensor_t = tensor.T
tensor_t

array([[list([1, 2, 3, 30]), list([1, 2, 3, 30]), list([1, 2, 3, 30])],
       [list([4, 5, 6, 31]), list([4, 5, 6, 31]), list([4, 5, 6, 31])],
       [list([7, 8, 932]), list([7, 8, 932]), list([7, 8, 932])]],
      dtype=object)

In [ ]:
tensor

array([[list([1, 2, 3, 30]), list([4, 5, 6, 31]), list([7, 8, 932])],
       [list([1, 2, 3, 30]), list([4, 5, 6, 31]), list([7, 8, 932])],
       [list([1, 2, 3, 30]), list([4, 5, 6, 31]), list([7, 8, 932])]],
      dtype=object)

In [ ]:
matriz_t_t = matriz_t.T
matriz_t_t

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
matriz

array([[1, 2],
       [3, 4],
       [5, 6]])

In [23]:
A = np.array([[1,2],[3,4],[5,6]])
B = np.array([[6,5],[4,3],[2,1]])
C = A+B
print(A)
print(B)
print(C)

[[1 2]
 [3 4]
 [5 6]]
[[6 5]
 [4 3]
 [2 1]]
[[7 7]
 [7 7]
 [7 7]]


In [27]:
D = matriz + escalar
print(D)

[[ 6.679  7.679]
 [ 8.679  9.679]
 [10.679 11.679]]
